version: '3.8'

services:
  web:
    build: .
    container_name: kuhaku_web
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/kuhaku_blog
      - USE_MOCK=True
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:7.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
